Algoritmo "semnome"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Nelio Alves 
// Descrição   : Área do Círculo
// Autor(a)    : Thiago da Costa
// Data atual  : 10/02/2021
Var
// Seção de Declarações das variáveis 

   raio, area : real
   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe o raio do círculo: ")
   leia(raio)


   area <- Pi * raio * raio)
   escreva("Area: ", area:6:3)

Fimalgoritmo